name: Start Redis server with remove container on exit flag

on: [push, pull_request]

jobs:
  redis-action:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        redis-version: [5, 6, 7]

    name: Start Redis Server v${{ matrix.redis-version }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Start Redis Server
        uses: ./
        with:
          redis-version: ${{ matrix.redis-version }}
          redis-remove-container-on-exit: true  # false by default
